progtech/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('technology.urls')),


]

technology/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
import datetime
from .mail import send_mail


class Chat(models.Model):
    """
        Сообщение из чата
        Поля:
            Дата создания
            От пользователя
            Сообщение
            Группа пользователя
    """
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    message = models.CharField(max_length=200)
    group = models.ForeignKey('Group', default='')

    def __str__(self):
        return self.message


class Group(models.Model):
    """
        Группа
        Поля:
            Факультет
            Номер группы
    """
    departament = models.CharField(max_length=300, verbose_name='Кафедра')
    name = models.CharField(max_length=300, verbose_name="Наименование")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = "Группы"


STATUS_CHOICES = (
    ('Не зачет', 'Не зачет'),
    ('Удволитворительно', 'Удволитворительно'),
    ('Хорошо', 'Хорошо'),
    ('Отлично', 'Отлично'),
)


def make_upload_path(instance,filename):
    """
    Создание загрузочной папки
    :param instance:
    :param filename:
    :return:
    """
    filename = str(datetime.datetime.now()) + "_" + filename
    return u'reports/%s/%s' % (instance.user.user, filename)


class Report(models.Model):
    """
        Отчет по лаборатоной
        Поля:
            Лабораторная - ForeignKey - Laboratory
            Пользователь - ForeignKey
            Отчет - FileField
            Балл - IntegerField
            Оценка - CharField
            Замечания - TextField
            Дата создания - DateTimeField
    """
    laboratory = models.ForeignKey('Laboratory', default='', related_name="reports", verbose_name='Отчеты')
    user = models.ForeignKey('UserGroup', default='', verbose_name="Студенты")
    report = models.FileField(upload_to=make_upload_path, verbose_name="Отчет")
    rating = models.IntegerField(default=1, blank=True, null=True, verbose_name="Баллы")
    price = models.CharField(choices=STATUS_CHOICES, max_length=300, blank=True, null=True, verbose_name="Оценка")
    note = models.TextField(verbose_name="Комментарий", default="", blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True,  null=True, blank=True)

    def __str__(self):
        return self.laboratory.name

    class Meta:
        verbose_name = 'Отчет'
        verbose_name_plural = "Отчеты"
        ordering = ['-date_create']

    def save(self, *args, **kwargs):
        """
        :param args:
        :param kwargs:
        :return:
        """
        if self.pk is not None:
            original = Report.objects.get(pk=self.pk)
            if original.report != self.report:
                self.note = ''
                self.date_create = datetime.datetime.now()
            send_mail(self)
        super(Report, self).save(*args, **kwargs)


class Laboratory(models.Model):
    """
        Лабораторная работа
        Поля:
            Название работы
            Описание
            Максимальный бал
            Вариант
            Группа
    """
    name = models.CharField(max_length=300, verbose_name="Название")
    description = RichTextField(verbose_name="Описание")
    max_rating = models.IntegerField(default=1, verbose_name="Максимальный балд")
    variant = models.IntegerField(default=0, verbose_name="Вариант")
    group = models.ForeignKey('Group', default=0, verbose_name="Группа")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Лабораторная работа'
        verbose_name_plural = "Лабораторные работы"


class UserGroup(models.Model):
    """
        Пользователь в группе
        Поля:
            Пользователь
            Группа
            Вариант
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Студенты")
    group = models.ForeignKey('Group', verbose_name="Группа")
    variant = models.IntegerField(default=0, verbose_name="Вариант")

    def __str__(self):
        return self.user.last_name + ' ' + self.user.first_name

    class Meta:
        ordering = ['-variant']
        verbose_name = 'Студент'
        verbose_name_plural = "Студенты"

templates/teacher/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Технологии программирования</title>
        <link rel="stylesheet" href="{% static 'css/chat.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     <script src="https://code.jquery.com/jquery-migrate-1.4.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src='//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML'></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Технологии программирования</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                 <li><a href="/admin">Панель администрирования</a></li>
                <li><a href="/logout">Выход</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
{% block script %}
{% endblock %}
        <script src="{% static 'js/chat.js' %}"></script>
</html>

templates/teacher/chat.html
{% extends 'teacher/base.html' %}
{% block content %}
    <div
    <div class="col-md-12" style="position: relative;">
            <div id="chat-body" class="panel panel-default">
                <div class="panel-heading">Чат</div>
                <div id="msg-list-div" class="panel-body">
                    <ul id="msg-list" class="list-group">
                        {% for obj in chat %}
                            {% if obj.user == request.user %}
                                <li class="text-right list-group-item">
                                    {{ obj.first_name }}<br>
                                    {{ obj.message }}
                                </li>
                            {% else %}
                                <li class="text-left list-group-item">{{ obj.message }}</li>
                            {% endif %}
                        {% empty %}
                            <li class="text-right list-group-item">No messages yet!</li>
                        {% endfor %}
                        <script>
                            var chatlist = document.getElementById('msg-list-div');
                            chatlist.scrollTop = chatlist.scrollHeight;
                        </script>
                    </ul>
                </div>
            </div>
            <form id="chat-form" method="post" action="/post/" style=" margin-bottom: 0;">
                <div id="chat-bottom" class="input-group">
                    <input type="text" autocomplete="off" id="chat-msg" name="chat-msg" class="form-control"/>
                    <input type="hidden" value="{{ g.id }}" name="group" id="group"/>
                    <span class="input-group-btn">
                    <input class="btn btn-default" id="send" type="submit" value="Отправить"/>
                    </span>
                </div>
            </form>
        </div>
{% endblock %}
{% block script %}
 {% endblock %}

templates/teacher/groups.html
{% extends 'teacher/base.html' %}
{% block content %}
<div class="container">
  <h2>Группы</h2>
  <p>Выберите группу для проверки студентов. </p>
  <table class="table">
    <thead>
      <tr>
        <th>Группа</th>
          <th>Чат группы</th>
      </tr>
    </thead>
    <tbody>
    {% for group in userGroup %}
      <tr>
        <td><a href="{% url 'students' group.id  %}">{{ group }}</a></td>
        <td><a href="{% url 'chat' group.id %}">Открыть</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/teacher/laboratory.html
{% extends 'teacher/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>{{ laboratory.laboratory.name }}</h2>
            <h4>Студент: {{ laboratory.user }} </h4>
            <h5>Вариант: {{ laboratory.laboratory.variant }} </h5>
            <br>
            <br>
            <div>
                <form method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputFile">Описание</label>
                        <p>{{ laboratory.laboratory.description |safe }}</p>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Отчет</label>
                        <p><a href="/media/{{ laboratory.report }}" target="_blank"> Открыть </a></p>
                    </div>
                    <div class="form-group">
                        <label>{{ form.rating.label }}</label>
                        <input name="rating" id="rating"  class="form-control" value='{{ form.rating.value}}'>
                    </div>
                    <div class="form-group">
                        <label>{{ form.price.label }}</label>
                        {{ form.price }}
                    </div>
                    <div class="form-group">
                        <label>{{ form.note.label }}</label>
                        {{ form.note }}
                    </div>
                    <button type="submit" class="btn btn-default">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('#id_price').addClass("form-control");
    $('#id_note').addClass("form-control");
</script>
{% endblock %}

templates/teacher/student.html
{% extends 'teacher/base.html' %}
{% block content %}
<div class="container">
  <h2>Лабораторные работы студента {{ student }} </h2>
  <p>Выберите лабораторные работу для проверки. </p>
  <table class="table">
    <thead>
      <tr>
        <th>Лабораторные работы</th>
        <th>Оценка</th>
        <th>Балл</th>
      </tr>
    </thead>
    <tbody>
    {% for reports in report %}
      <tr>
        <td><a href="{% url 'laboratory' id_group=group.id id_student=user.user.id id=reports.id %}">{{ reports.laboratory.name }}</a></td>
        <td><a >{{ reports.price }}</a></td>
        <td><a >{{ reports.rating }}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/teacher/students.html
{% extends 'teacher/base.html' %}
{% block content %}
<div class="container">
    <h2>Студенты</h2>
    <p>Выберите студента для проверки. </p>
    <table class="table">
        <thead>
        <tr>
            <th>Студент</th>
            <th>Вариант</th>
            <th>Группа</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td><a href="{% url 'student' id=student.user_id id_group=group.id %}">{{ student }}</a></td>
                <td>{{ student.variant }}</td>
                <td>{{ student.group }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}